MVC5OnlineTicariOtomasyon/Models/Classes/Departman.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVC5OnlineTicariOtomasyon.Models.Classes
{
	public class Departman
	{
		[Key]
		public int Departmanid { get; set; }
		[Column(TypeName = "Varchar")]
		[StringLength(30)]
		public string DepartmanAd { get; set; }
		public bool Durum { get; set; }
		public ICollection<Personel> Personels { get; set; }

	}
}

MVC5OnlineTicariOtomasyon/Controllers/DepartmanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC5OnlineTicariOtomasyon.Models.Classes;
namespace MVC5OnlineTicariOtomasyon.Controllers
{
    public class DepartmanController : Controller
    {
        // GET: Departman

        Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.Departmans.Where(x=>x.Durum==true).ToList();
            return View(degerler);
        }

        [HttpGet]
        public ActionResult DepartmanEkle()
		{
            return View();
		}
        [HttpPost]
        public ActionResult DepartmanEkle(Departman d)
		{
            d.Durum = true;
            c.Departmans.Add(d);
            c.SaveChanges();
            return RedirectToAction("Index");
		}

        public ActionResult DepartmanSil(int id)
		{
            var dep = c.Departmans.Find(id);
            dep.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DepartmanGetir (int id)
		{
            var dpt = c.Departmans.Find(id);
            return View("DepartmanGetir", dpt);
		}

        public ActionResult DepartmanGuncelle(Departman p)
		{
            var dept = c.Departmans.Find(p.Departmanid);
            dept.DepartmanAd = p.DepartmanAd;
            c.SaveChanges();
            return RedirectToAction("Index");

		}

        public ActionResult DepartmanDetay(int id)
		{
            var degerler = c.Personels.Where(x => x.Departmanid==id).ToList();
            var dpt = c.Departmans.Where(x => x.Departmanid == id).Select(y => y.DepartmanAd).FirstOrDefault();
            ViewBag.d = dpt;
            return View(degerler);
		}
        public ActionResult DepartmanSatis(int id)
		{
            var degerler = c.SatisHarekets.Where(x => x.Personelid == id).ToList();
            var per = c.Personels.Where(x => x.PersonelId == id).Select(y => y.PersonelAd +" "+ y.PersonelSoyad).FirstOrDefault();
            ViewBag.dpers = per;
            return View(degerler);
		}
    }
}

MVC5OnlineTicariOtomasyon/Views/Departman/DepartmanDetay.cshtml
@using MVC5OnlineTicariOtomasyon.Models.Classes
@model List<Personel>
@{
    ViewBag.Title = "DepartmanDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>DepartmanDetay</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Departman Adı : @ViewBag.d</li>

</ol>
<table class="table table-hover">
    <tr>
        <th>Personel Id</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Görsel</th>
        <th>Satış Detayı</th>
    </tr>
    @foreach(var x in Model)
			{
                <tr>
                    <td>@x.PersonelId</td>
                    <td>@x.PersonelAd</td>
                    <td>@x.PersonelSoyad</td>
                    <td>@x.PersonelGorsel</td>
                    <td><a href="/Departman/DepartmanSatis/@x.PersonelId" class="btn btn-default" style="background-color:orangered">Satışlar</a></td>
                </tr>
			}
    <tr></tr>
</table>

MVC5OnlineTicariOtomasyon/Views/Departman/DepartmanEkle.cshtml
@model MVC5OnlineTicariOtomasyon.Models.Classes.Departman
@{
    ViewBag.Title = "DepartmanEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Departman Ekle</h2>


<form class="form-group" method="post">

    @Html.LabelFor(x => x.DepartmanAd)
    @Html.TextBoxFor(x => x.DepartmanAd, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Kaydet </button>
</form>

MVC5OnlineTicariOtomasyon/Views/Departman/DepartmanGetir.cshtml
@model MVC5OnlineTicariOtomasyon.Models.Classes.Departman
@{
    ViewBag.Title = "DepartmanGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>DepartmanGetir</h2>
@using (Html.BeginForm("DepartmanGuncelle", "Departman", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(x => x.Departmanid)
        @Html.TextBoxFor(x => x.DepartmanAd, new { @class = "form-control" })
        @Html.HiddenFor(x => x.Departmanid)
    </div>
    <button class="btn btn-warning">Güncelle </button>
}

MVC5OnlineTicariOtomasyon/Views/Departman/DepartmanSatis.cshtml
@using MVC5OnlineTicariOtomasyon.Models.Classes
@model List<SatisHareket>

@{
    ViewBag.Title = "DepartmanSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Departman Satis</h2>
<br />
<ol class="breadcrumb mb-4">

<li class="breadcrumb-item active" >Personel adı : @ViewBag.dpers</li>
</ol>
<table class="table table-condensed">
    <tr>
        <th>Satış Id</th>
        <th>Ürün</th>
        <th>Cari</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Yazdır</th>
    </tr>
    @foreach(var x in Model)
			{
        <tr>
            <td>
                @x.Satisid
            </td>
            <td>@x.Urun.UrunAd</td>
            <td>@x.Cari.CariAd @x.Cari.CariSoyad</td>
            <td>@x.Fiyat</td>
            <td>@x.Adet</td>
            <td>@x.ToplamTutar</td>
            <td>@x.Tarih</td>
            <td><a href="#" class="btn btn-default" style="background-color:dodgerblue">Yazdır</a></td>
        </tr>
			}
</table>

MVC5OnlineTicariOtomasyon/Views/Departman/Index.cshtml
@using MVC5OnlineTicariOtomasyon.Models.Classes;
@model List<Departman>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Departman Sayfası</h2>

<table class="table table-bordered">

    <tr>
        <td> ID</td>
        <td> Departman</td>
        <td> Sil</td>
        <td> Güncelle</td>
        
    </tr>
    @foreach (var k in Model)
    {
        <tr>
            <td>@k.Departmanid</td>
            <td>@k.DepartmanAd</td>

            <td><a href="/Departman/DepartmanSil/@k.Departmanid" class="btn btn-danger">Sil</a></td>
            <td><a href="/Departman/DepartmanGetir/@k.Departmanid" class="btn btn-success">Güncelle</a></td>
        </tr>
    }
    </table>
<a href="/Departman/DepartmanEkle" class="btn btn-primary"> Departman Ekle</a></a>