MVC5OnlineTicariOtomasyon/Models/Classes/Personel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVC5OnlineTicariOtomasyon.Models.Classes
{
	public class Personel
	{
		[Key]
		public int PersonelId { get; set; }
		[Column(TypeName = "Varchar")]
		[StringLength(30)]
		public string PersonelAd { get; set; }
		[Column(TypeName = "Varchar")]
		[StringLength(30)]
		public string PersonelSoyad { get; set; }
		[Column(TypeName = "Varchar")]
		[StringLength(250)]
		public string PersonelGorsel { get; set; }
		public virtual Departman Departman { get; set; }
		public int Departmanid { get; set; }
		public ICollection<SatisHareket> SatisHarekets { get; set; }
	}
}

MVC5OnlineTicariOtomasyon/Controllers/PersonelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC5OnlineTicariOtomasyon.Models.Classes;
namespace MVC5OnlineTicariOtomasyon.Controllers
{
    public class PersonelController : Controller
    {
        // GET: Personel
        Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.Personels.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult PersonelEkle()
        {
            List<SelectListItem> deger1 = (from x in c.Departmans.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.DepartmanAd,
                                               Value = x.Departmanid.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            return View();
        }
         [HttpPost]
         public ActionResult PersonelEkle(Personel p)
        {
            c.Personels.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult PersonelSil(int id)
        {
           
            return RedirectToAction("Index");
        }

        public ActionResult PersonelGetir(int id)
        {
            List<SelectListItem> deger1 = (from x in c.Departmans.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.DepartmanAd,
                                               Value = x.Departmanid.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            var prs = c.Personels.Find(id);
            return View("PersonelGetir", prs);
            
        }

        public ActionResult PersonelGuncelle (Personel p)
		{
            var persn = c.Personels.Find(p.PersonelId);
            persn.PersonelAd = p.PersonelAd;
            persn.PersonelSoyad = p.PersonelSoyad;
            persn.PersonelGorsel = p.PersonelGorsel;
            persn.Departmanid = p.Departmanid;
            c.SaveChanges();
            return RedirectToAction("Index");

        }


        public ActionResult PersonelListele()
        {
            return View();
        }

    }

}

MVC5OnlineTicariOtomasyon/Views/Personel/Index.cshtml
@using MVC5OnlineTicariOtomasyon.Models.Classes
@model List<Personel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Personeller</h2>

<table class="table table-bordered">

    <tr>
        <td> ID</td>
        <td> Personel Adı</td>
        <td> Soyadı</td>
        <td> Görsel</td>
        <td> Departman</td>
        <td>Sil</td>
        <td>Güncelle</td>
        <td>Detaylar</td>
    </tr>

    @foreach (var u in Model)
    {
<tr>
    <td>@u.PersonelId</td>
    <td>@u.PersonelAd</td>
    <td>@u.PersonelSoyad</td>
    <td>@u.PersonelGorsel</td>
    <td>@u.Departman.DepartmanAd</td>

    <td>  <a href="/Personel/PersonelSil/" class="btn btn-danger">Sil</a></td>
    <td>  <a href="/Personel/PersonelGetir/@u.PersonelId" class="btn btn-warning ">Güncelle</a></td>
    <td>  <a href="/Departman/DepartmanSatis/@u.PersonelId" class="btn btn-default" style="background-color:lightcoral">Detaylar</a></td>


</tr>

        }

    </table>
<a href="/Personel/PersonelEkle" class="btn btn-primary"> Personel Ekle</a></a>

MVC5OnlineTicariOtomasyon/Views/Personel/PersonelEkle.cshtml
@model MVC5OnlineTicariOtomasyon.Models.Classes.Personel
@{
    ViewBag.Title = "PersonelEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>PersonelEkle</h2>
<form class="form-group" method="post">
    @Html.LabelFor(x => x.PersonelAd)
    @Html.TextBoxFor(x => x.PersonelAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.PersonelSoyad)
    @Html.TextBoxFor(x => x.PersonelSoyad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.PersonelGorsel)
    @Html.TextBoxFor(x => x.PersonelGorsel, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.Departman.Departmanid)
    @Html.DropDownListFor(x => x.Departmanid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })



    <button class="btn btn-info">Kaydet </button>

</form>

MVC5OnlineTicariOtomasyon/Views/Personel/PersonelGetir.cshtml
@model MVC5OnlineTicariOtomasyon.Models.Classes.Personel
@{
    ViewBag.Title = "PersonelGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


<h2>Personel  Bilgisi Güncelle</h2>

<br />
@using (Html.BeginForm("PersonelGuncelle", "Personel", FormMethod.Post))
{

<div class="form-group">
    @Html.HiddenFor(x => x.PersonelId)
    @Html.LabelFor(x => x.PersonelAd)
    @Html.TextBoxFor(x => x.PersonelAd, new { @class = "form-control" })

    <br />
    @Html.LabelFor(x => x.PersonelSoyad)
    @Html.TextBoxFor(x => x.PersonelSoyad, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.PersonelSoyad, "", new { @style = "color:red" })
    <br />
    @Html.LabelFor(x => x.PersonelGorsel)
    @Html.TextBoxFor(x => x.PersonelGorsel, new { @class = "form-control" })

    <br />
    @Html.LabelFor(x => x.Departman.Departmanid)
    @Html.DropDownListFor(x => x.Departmanid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />

    <button class="btn btn-default" style="background-color:yellowgreen">Güncelle</button>
    
</div>
}

MVC5OnlineTicariOtomasyon/Views/Personel/PersonelListele.cshtml
@using MVC5OnlineTicariOtomasyon.Models.Classes
@model List<Personel>
@{
    ViewBag.Title = "PersonelListele";
    Layout = "~/Views/Shared/AdminLayout.cshtml";

}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Contacts</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Contacts</h1>
                    </div>

                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="card card-solid">
                <div class="card-body pb-0">
                    <div class="row d-flex align-items-stretch">


                        <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                            @foreach (var x in Model)
                            {
                                <div class="card bg-light">
                                    <div class="card-header text-muted border-bottom-0">
                                        Digital Strategist
                                    </div>
                                    <div class="card-body pt-0">
                                        <div class="row">
                                            <div class="col-7">
                                                <h2 class="lead"><b>@x.PersonelAd+@x.PersonelSoyad</b></h2>
                                                <p class="text-muted text-sm"><b>About: </b> Web Designer / UX / Graphic Artist / Coffee Lover </p>
                                                <ul class="ml-4 mb-0 fa-ul text-muted">
                                                    <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Address: Demo Street 123, Demo City 04312, NJ</li>
                                                    <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone #: + 800 - 12 12 23 52</li>
                                                </ul>
                                            </div>
                                            <div class="col-5 text-center">
                                                <img src="../../dist/img/user2-160x160.jpg" alt="" class="img-circle img-fluid">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-footer">
                                        <div class="text-right">
                                            <a href="#" class="btn btn-sm bg-teal">
                                                <i class="fas fa-comments"></i>
                                            </a>
                                            <a href="#" class="btn btn-sm btn-primary">
                                                <i class="fas fa-user"></i> View Profile
                                            </a>
                                        </div>
                                    </div>
                                </div>
                       
                        }
                        </div>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <nav aria-label="Contacts Page Navigation">
                            <ul class="pagination justify-content-center m-0">
                                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item"><a class="page-link" href="#">4</a></li>
                                <li class="page-item"><a class="page-link" href="#">5</a></li>
                                <li class="page-item"><a class="page-link" href="#">6</a></li>
                                <li class="page-item"><a class="page-link" href="#">7</a></li>
                                <li class="page-item"><a class="page-link" href="#">8</a></li>
                            </ul>
                        </nav>
                    </div>
                    <!-- /.card-footer -->
                </div>
                <!-- /.card -->

            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        <footer class="main-footer">
            <div class="float-right d-none d-sm-block">
                <b>Version</b> 3.0.4
            </div>
            <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
            reserved.
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>

        <script src="../../plugins/jquery/jquery.min.js"></script>
        <!-- Bootstrap 4 -->
        <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
        <!-- AdminLTE App -->
        <script src="../../dist/js/adminlte.min.js"></script>
        <!-- AdminLTE for demo purposes -->
        <script src="../../dist/js/demo.js"></script>
    </body>
</html>